on:
  push:

name: Playground

jobs:
  cargo-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: --allow-dirty

  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"
      - name: Build wasm
        run: |
          wasm-pack build --release
          mv valve_kv_tools.d.ts pkg/
      - name: Setup Playground
        run: cd playground && npm i && npm run build
      - name: Get version
        run: |
          tmp=$(cargo pkgid)
          tmp=$(${a#*@})
          echo "PACKAGE_VERSION=$(echo $tmp)" >> $GITHUB_ENV
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: playground/dist
